version: '2'

services:

    wordpress:
        image: wordpress
        ports:
            - 8080:88
        environment:
            WORDPRESS_DB_PASSWORD: r00t1f13d

    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: r00t1f13d
